<a href="https://colab.research.google.com/github/eanxgeek/QECamp19-Intro-to-pandas/blob/master/sqlalchemy_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### This is a very simple demo using sqlalchemy to engage a database and create a dataframe from the query results.

In [0]:
from sqlalchemy import create_engine
import os
import configparser
import pandas as pd
import numpy as np

In [0]:
home = os.path.expanduser('~')
cf = home+'/.jira.ini'

config = configparser.ConfigParser()
config.read(cf)

u = config['PGSQL']['username']
p = config['PGSQL']['password']

In [0]:
prod_uri = f'postgresql://{u}:{p}@polarion-node-01.hosts.prod.upshift.eng.rdu2.redhat.com:5432/polarion'
sql = "SELECT * from polarion.workitem where c_type = 'requirement'"

In [0]:
engine = create_engine(prod_uri, client_encoding='utf8')

In [0]:
with engine.connect() as con:
    con.execute('SET search_path TO polarion')
    rs = con.execute(sql)
    df = pd.DataFrame(rs.fetchall())

In [6]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,6764377,6764377,5772012,False,70898,70898,2018-04-18 23:08:37.794,text/html:\n<p>This feature request summaries ...,None,EAP7-298036,...,None,NaT,must_have,draft,None,None,NaN,Enhancements and new features in HAL 3.x,requirement,2018-07-04 23:08:55.804
1,6764378,6764378,5772012,False,70898,70898,2018-04-18 23:08:37.893,None,None,EAP7-298037,...,None,NaT,must_have,draft,None,None,NaN,Add support for the proxy protocol,requirement,2018-04-18 23:08:38.561
2,216559,216559,5772012,False,70898,70898,2018-04-25 23:08:41.540,"text/html:\n<p>If ee8.preview.mode is set, Wil...",None,EAP7-298315,...,None,NaT,must_have,approved,None,None,NaN,JPA 2.2 Support,requirement,2018-08-07 10:49:41.398
3,6768024,6768024,5772012,False,4846,4846,2018-09-15 13:14:13.840,None,None,POLA-789,...,None,NaT,must_have,draft,None,None,NaN,test for new prod asdas,requirement,2018-09-15 13:14:33.377
4,6764382,6764382,5772012,False,70898,70898,2018-05-07 13:19:35.679,"text/html:\n<p>Please see <a href=""https://iss...",None,EAP7-298470,...,None,NaT,must_have,draft,None,None,NaN,Add setting to control global memory usage for...,requirement,2018-05-07 13:19:36.516

## Check out these result keys

In [6]:
rs.keys()

['c_pk',
 'c_uri',
 'c_rev',
 'c_deleted',
 'fk_author',
 'fk_uri_author',
 'c_created',
 'c_description',
 'c_duedate',
 'c_id',
 'c_initialestimate',
 'c_location',
 'fk_module',
 'fk_uri_module',
 'c_outlinenumber',
 'c_plannedend',
 'c_plannedstart',
 'c_previousstatus',
 'c_priority',
 'fk_project',
 'fk_uri_project',
 'c_remainingestimate',
 'c_resolution',
 'c_resolvedon',
 'c_severity',
 'c_status',
 'fk_timepoint',
 'fk_uri_timepoint',
 'c_timespent',
 'c_title',
 'c_type',
 'c_updated']

## Convert the dataframe columns to rs.keys

In [0]:
df.columns = rs.keys()

In [8]:
df.head()

,c_pk,c_uri,c_rev,c_deleted,fk_author,fk_uri_author,c_created,c_description,c_duedate,c_id,...,c_resolution,c_resolvedon,c_severity,c_status,fk_timepoint,fk_uri_timepoint,c_timespent,c_title,c_type,c_updated
0,6764378,6764378,5772012,False,70898,70898,2018-04-18 23:08:37.893,None,None,EAP7-298037,...,None,NaT,must_have,draft,None,None,NaN,Add support for the proxy protocol,requirement,2018-04-18 23:08:38.561
1,6768024,6768024,5772012,False,4846,4846,2018-09-15 13:14:13.840,None,None,POLA-789,...,None,NaT,must_have,draft,None,None,NaN,test for new prod asdas,requirement,2018-09-15 13:14:33.377
2,6764382,6764382,5772012,False,70898,70898,2018-05-07 13:19:35.679,"text/html:\n<p>Please see <a href=""https://iss...",None,EAP7-298470,...,None,NaT,must_have,draft,None,None,NaN,Add setting to control global memory usage for...,requirement,2018-05-07 13:19:36.516
3,6764431,6764431,5782509,False,70898,70898,2018-06-13 23:08:43.389,"text/html:\nWeb console part of <a class=""issu...",None,EAP7-299639,...,None,NaT,must_have,draft,None,None,NaN,Support Eclipse MicroProfile Config in Web Con...,requirement,2019-01-09 23:08:53.169
4,214649,214649,5782509,False,70898,70898,2018-06-13 23:08:43.477,text/html:\nSupport Eclipse MicroProfile Confi...,None,EAP7-299640,...,None,NaT,must_have,draft,None,None,NaN,Support Eclipse MicroProfile Config,requirement,2019-01-09 23:08:53.169

## Let's replace None with NumPy's NaN

In [0]:
df.fillna(value=pd.np.nan, inplace=True)

In [10]:
df.head()

,c_pk,c_uri,c_rev,c_deleted,fk_author,fk_uri_author,c_created,c_description,c_duedate,c_id,...,c_resolution,c_resolvedon,c_severity,c_status,fk_timepoint,fk_uri_timepoint,c_timespent,c_title,c_type,c_updated
0,6764378,6764378,5772012,False,70898,70898,2018-04-18 23:08:37.893,NaN,NaN,EAP7-298037,...,NaN,NaT,must_have,draft,NaN,NaN,NaN,Add support for the proxy protocol,requirement,2018-04-18 23:08:38.561
1,6768024,6768024,5772012,False,4846,4846,2018-09-15 13:14:13.840,NaN,NaN,POLA-789,...,NaN,NaT,must_have,draft,NaN,NaN,NaN,test for new prod asdas,requirement,2018-09-15 13:14:33.377
2,6764382,6764382,5772012,False,70898,70898,2018-05-07 13:19:35.679,"text/html:\n<p>Please see <a href=""https://iss...",NaN,EAP7-298470,...,NaN,NaT,must_have,draft,NaN,NaN,NaN,Add setting to control global memory usage for...,requirement,2018-05-07 13:19:36.516
3,6764431,6764431,5782509,False,70898,70898,2018-06-13 23:08:43.389,"text/html:\nWeb console part of <a class=""issu...",NaN,EAP7-299639,...,NaN,NaT,must_have,draft,NaN,NaN,NaN,Support Eclipse MicroProfile Config in Web Con...,requirement,2019-01-09 23:08:53.169
4,214649,214649,5782509,False,70898,70898,2018-06-13 23:08:43.477,text/html:\nSupport Eclipse MicroProfile Confi...,NaN,EAP7-299640,...,NaN,NaT,must_have,draft,NaN,NaN,NaN,Support Eclipse MicroProfile Config,requirement,2019-01-09 23:08:53.169